---
# Name your file secrets.yml

development:
  DB_FILENAME: db/local/dev.db
  GITHUB_TOKEN: create_github_token
  REPOSTORE_PATH: repostore
  API_HOST: http://localhost:9090

app_test:
  DB_FILENAME: db/local/test.db
  REPOSTORE_PATH: repostore
  API_HOST: http://localhost:9090

test:
  DB_FILENAME: db/local/test.db
  GITHUB_TOKEN: create_github_token
  REPOSTORE_PATH: repostore
  API_HOST: http://localhost:9090

production:
  # - assign DATABASE_URL in production
  GITHUB_TOKEN: create_github_token
  REPOSTORE_PATH: repostore
  API_HOST: https://codepraise2022-api
