---
# Name your file secrets.yml

development:
  # Infrastructure
  DB_FILENAME: db/local/dev.db
  GITHUB_TOKEN: create_github_token
  REPOSTORE_PATH: repostore
  # Application
  APP_HOST: http://localhost:9000
  SESSION_SECRET: <some secret>

test:
  # Infrastructure
  DB_FILENAME: db/local/test.db
  GITHUB_TOKEN: create_github_token
  REPOSTORE_PATH: repostore
  # Application
  APP_HOST: http://localhost:9000
  SESSION_SECRET: <some secret>

production:
  # Infrastructure
  # - assign DATABASE_URL in production
  GITHUB_TOKEN: create_github_token
  REPOSTORE_PATH: repostore
  # Application
  APP_HOST: http://url.to.app
  SESSION_SECRET: <some secret>
